### ISSUE TITLE
Turn service inproc Rough Cut into QuickStart

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#100]
https://github.com/advantageous/qbit/wiki/%5BRough-Cut%5D-Working-with-inproc-Services

**Comment by RichardHightower** [comment]
Fadi take a look

**Comment by fadihub** [comment]
let me know what you think.

https://github.com/advantageous/qbit/wiki/%5BQuick-Start%5D-Working-with-inproc-MicroServices-within-QBit
