### ISSUE TITLE
Turn service inproc Rough Cut into [Detailed Tutorial]

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#101]
https://github.com/advantageous/qbit/wiki/%5BRough-Cut%5D-Working-with-inproc-Services

**Comment by RichardHightower** [comment]
Fadi take a look

**Comment by fadihub** [comment]
let me know what you think

https://github.com/advantageous/qbit/wiki/%5BDetailed-Tutorial%5D-Working-with-inproc-MicroServices-within-QBit.

**Comment by RichardHightower** [comment]
Will do

On Thursday, February 19, 2015, fadihub <notifications@github.com> wrote:

> let me know what you think
>
>
> https://github.com/advantageous/qbit/wiki/%5BDetailed-Tutorial%5D-Working-with-inproc-MicroServices-within-QBit
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/101#issuecomment-75017179>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
