### ISSUE TITLE
Release QBit to public repo

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#178]
Geoff, please cut a release at your earliest convenience.

**Comment by revelfire** [comment]
+1  

I had a dickens of a time getting it all loaded in and built :)

**Comment by RichardHightower** [comment]
Now it is getting built by travis. :) Thanks to sailor geoff..

**Comment by RichardHightower** [comment]
It builds now in travis again.

I added the maven stuff to qbit-servlet and qbit-jetty so those get built  and put into public repo.

Let's pull that trigger.

**Comment by RichardHightower** [comment]
Two releases so far 0.61! :)
