### ISSUE TITLE
build fails "No value has been specified for property 'mainClassName'"

### ISSUE THREAD

**Issue by mbacchi** [advantageous/qbit#221]
I can't get gradle to build successfully.  Here's my environment:
[qbit3]$ gradle -v
Gradle 2.3
Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Linux 3.18.7-100.fc20.x86_64 amd64

The error:

[qbit3]$ gradle clean build install
:startScripts FAILED
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':startScripts'.<br>
> No value has been specified for property 'mainClassName'.

Oddly, "gradle classes" and then "gradle test" both succeed.  Ideas?

I don't have any experience with gradle so not sure how to troubleshoot further.

Thanks,
-Matt

**Comment by RichardHightower** [comment]
Does not happen for me but the fix should be easy. I just need to add the
propery or remove the plugin.

Thanks for reporting it and sorry about that.

The gradle build needs some love.

It has accumulated too much cruft.



On Saturday, March 21, 2015, mbacchi <notifications@github.com> wrote:

> I can't get gradle to build successfully. Here's my environment:
> [qbit3]$ gradle -v
> Gradle 2.3
> Groovy: 2.3.9
> Ant: Apache Ant(TM) version 1.9.3 compiled on December 23 2013
> JVM: 1.8.0_31 (Oracle Corporation 25.31-b07)
> OS: Linux 3.18.7-100.fc20.x86_64 amd64
>
> The error:
>
> [qbit3]$ gradle clean build install
> :startScripts FAILED
> FAILURE: Build failed with an exception.
>
>    - What went wrong: A problem was found with the configuration of task
>    ':startScripts'.
>    > No value has been specified for property 'mainClassName'.
>
> Oddly, "gradle classes" and then "gradle test" both succeed. Ideas?
>
> I don't have any experience with gradle so not sure how to troubleshoot
> further.
>
> Thanks,
> -Matt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/221>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
Ok.. I took a stab at fixing this. Let me know if it works.

**Comment by mbacchi** [comment]
Thanks Richard.  Following your lead I made the following change, I would
fork and create a pull request but for a single line change I think its
unnecessary.  This builds now for me.  I'm planning to use qbit to learn
microservices I'm not really a web guy but was planning to write a small
todo microcervice app when I found qbit doing a google search.  I want to
get the test todo application running then will figure out how to write my
own.  Thanks again.

--- a/build.gradle
+++ b/build.gradle
@@ -388,7 +388,6 @@ project(':qbit-perf-server') {

 project(':qbit-admin') {

-    apply plugin: 'application'

     dependencies {
         compile project(':qbit-boon')

-Matt

**Comment by fadihub** [comment]
Hi Matt,

Thanks for your interest in QBit, i noticed  that you are interested in building Todo List app with QBit, we have done a simple one, it could be a good starting point for you. Check it out:
https://github.com/advantageous/qbit/wiki/%5BQuick-Start%5D-Building-a-single-page;-Todo-List-Application-with-QBit

Have a great day!
