### ISSUE TITLE
Could not find reflection lib or JSON parser

### ISSUE THREAD

**Issue by vach** [advantageous/qbit#228]
I'm trying out websocket client example here https://github.com/advantageous/qbit/wiki/%5BDoc%5D-Using-QBit-microservice-lib's-WebSocket-support

First of all the package org.boon where is it from? is there a maven artifact for it?
anyway i've used boon dependency which could cover this using io.advantageous.boon..

now it compiles but when i run it i get this:

Factory was null 
Exception in thread "main" java.lang.IllegalStateException: Could not find reflection lib or JSON parser
	at io.advantageous.qbit.QBit.registerReflectionAndJsonParser(QBit.java:64)
	at io.advantageous.qbit.QBit.doGetFactory(QBit.java:51)
	at io.advantageous.qbit.QBit.factory(QBit.java:39)
	at io.advantageous.qbit.http.server.HttpServerBuilder.build(HttpServerBuilder.java:193)
	at com.jarvis.sandbox.qbit.EchoWebSocket.main(EchoWebSocket.java:19)

**Comment by vach** [comment]
These are dependencies i have now

        <dependency>
            <groupId>io.advantageous.qbit</groupId>
            <artifactId>boon</artifactId>
            <version>0.7.2</version>
        </dependency>

        <dependency>
            <groupId>io.advantageous.qbit</groupId>
            <artifactId>qbit-core</artifactId>
            <version>0.7.2</version>
        </dependency>

**Comment by RichardHightower** [comment]
<dependency>
        <groupId>io.advantageous.qbit</groupId>
        <artifactId>boon</artifactId>
        <version>0.7.2</version>
    </dependency>

 <dependency>
        <groupId>io.advantageous.qbit</groupId>
        <artifactId>qbit-boon</artifactId>
        <version>0.7.2</version>
    </dependency>


<dependency> <groupId>io.advantageous.qbit</groupId>
<artifactId>qbit-core</artifactId> <version>0.7.2</version> </dependency>


Fadi has a bunch of example starter projects.

Of course they are all using gradle..


On Sun, Mar 29, 2015 at 3:20 AM, Vachagan Balayan <notifications@github.com>
wrote:

> These are dependencies i have now
>
>     <dependency>
>         <groupId>io.advantageous.qbit</groupId>
>         <artifactId>boon</artifactId>
>         <version>0.7.2</version>
>     </dependency>
>
>     <dependency>
>         <groupId>io.advantageous.qbit</groupId>
>         <artifactId>qbit-core</artifactId>
>         <version>0.7.2</version>
>     </dependency>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/228#issuecomment-87387874>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by fadihub** [comment]
Hi Vach,

In the link bellow you can find the example you're interested in, fully working. thanks for your interest.

https://github.com/fadihub/echo-websocket.git

https://github.com/advantageous/qbit/wiki/%5BDetailed-Tutorial%5D-Building-a-HTTP-server-with-WebSocket-support-using-QBit--(very-easy)
