### ISSUE TITLE
Clarification --Registration Check with Http 

### ISSUE THREAD

**Issue by nandhusriram** [advantageous/qbit#238]
I dont  see the registration check has an option for enabling HTTP check  , like this 
  "ID": "testserviceid",
  "Name": "testservice",
  "Address": "localhost",
  "Port": 8080,
  "Check": {
    "name": "HTTP API on port 8080",
    "HTTP": "http://localhost:8080/",
    "Interval": "10s"
  }

}

Is there a way to do that ?

**Comment by RichardHightower** [comment]
There is a way. It needs to be documented.

**Comment by RichardHightower** [comment]
Look at AdminBuilder and HealthService.

The Admin endpiont has an ok method.

You register services with the HealthService, the services will ttl to the HealthService which will agregate the results to one check point hittable from Nagios or whatever. 

There are other ways too. It will be in the next release which comes out today.

If you want further details, hit me up on the google group for qbit.
