### ISSUE TITLE
Question: Is it possible to dynamically configure listeners on the event bus

### ISSUE THREAD

**Issue by plenderyou** [advantageous/qbit#246]
I probably have missed it in the documentation but is it possible to dynamically register a service on the event bus (channel)?

I see we can mark a method with the @OnEvent(NEW_HIRE_CHANNEL) annotation but I'd like to bind the channel name at runtime.

The reason being is that we have a Proxy service that routes to many downstream services depending on some http request parameters in our case many different wallets for different integrations so the client proxy would 

eventManager.send( WALLET_CHANNEL + walletId, transfer);

And each service would register on their own channel.

**Comment by RichardHightower** [comment]
It is. Look at the code that does the distributed event bus. Look at EventBus and EventConnector.

io.advantageous.qbit.events.spi.EventConnector

Also can you please reask this on the qbit mailing list, and I will go into a lot more detail.

EventManagerBuilder takes a EventConnector

EventConnectorHub implements EventConnector and manages a group of EventConnectors.

Check out the code and see where those are being used. 

Subscribe to the mailing list and I will go into more detail.
