### ISSUE TITLE
QBit failure with multiple http verb support method={RequestMethod.POST,RequestMethod.PUT}

### ISSUE THREAD

**Issue by revelfire** [advantageous/qbit#249]
https://gist.github.com/revelfire/24e381c5bb12056d42f3

**Comment by revelfire** [comment]
Resolved by pull request #259. (Please review my todo comment and let me know if an additional check needs to be implemented.)

**Comment by RichardHightower** [comment]
Will do.

On Sunday, June 7, 2015, revelfire <notifications@github.com> wrote:

> Resolved by pull request #259
> <https://github.com/advantageous/qbit/pull/259>. (Please review my todo
> comment and let me know if an additional check needs to be implemented.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/249#issuecomment-109802241>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
