### ISSUE TITLE
FIX FOR NEXT RELEASE- SET TO DEBUG LOGGING (NOTE TO ME) Known URI paths are no longer printed after upgrading from 0.7.2 to 0.8.x

### ISSUE THREAD

**Issue by mfronczyk** [advantageous/qbit#253]
At version 0.7.2 I get the following log message when I try to hit an incorrect URL:

    No service at method address /services/myapp/tilesservice/pin method name  object name null
    SERVICES[/services/myapp/tilesservice/TAKETILE, qbitTilesService, /services/myapp/tilesservice, /services/myapp/tilesservice/taketile/, /services/myapp/tilesservice/taketile, /services/myapp/tilesservice/ping, /services/myapp/tilesservice/takeTile, /services/myapp/tilesservice/PING]

    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/TAKETILE
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path qbitTilesService
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/taketile/
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/taketile
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/ping
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/takeTile
    2015-06-06 18:46:54.588 ERROR 2261 --- [/services/myapp] i.a.qbit.service.impl.ServiceBundleImpl  : known URI path /services/myapp/tilesservice/PING

And the JSON response I get is:

    {"address":"/services/myapp/tilesservice/pin","detailMessage":"there is no object at this address: /services/myapp/tilesservice/pin\n method name=\n objectName=null Service Address not found","cause":"io.advantageous.qbit.service.ServiceMethodNotFoundException: there is no object at this address: /services/myapp/tilesservice/pin
     method name=
     objectName=null Service Address not found"}

This is very helpful for debugging, because you can immediately see what paths are registered.

In the 0.8.7 version (it started from 0.8.0 though) I only see this when I hit a wrong URL:

    ["Unable to find handler"]

But everything works fine if I fix the URL. However, the previous messages were much more helpful. When I saw that I didn't know what's going on.

I checked in the code and the most recent version still contains the logging of known paths, but the breakpoint there isn't hit when the URL is incorrect.

I based my service on the qbit and spring boot integration tutorial. I didn't do any code changes after upgrading from 0.7.2 to 0.8.0.

Is there a way to restore that behaviour in 0.8.x?

**Comment by RichardHightower** [comment]
Code is still there.

```java
        if (methodCallConsumer == null) {
            logger.error("No service at method address " + methodCall.address()
                    + " method name " + methodCall.name() + " object name " + methodCall.objectName() + "\n SERVICES" + serviceMapping.keySet() + "\n");

            Set<String> uris = serviceMapping.keySet();

            //noinspection CodeBlock2Expr
            uris.forEach((String it) -> {
                logger.error("known URI path " + it);
            });

            throw new ServiceMethodNotFoundException("there is no object at this address: " + methodCall.address()
                    + "\n method name=" + methodCall.name() + "\n objectName=" + methodCall.objectName(), methodCall.address());
        }

```

I wonder if you have disabled logging somehow?

**Comment by mfronczyk** [comment]
Yes, I wrote that the code is still there, but it isn't executed.

**Comment by RichardHightower** [comment]
aha

**Comment by RichardHightower** [comment]
It is only for REST calls not WebSocket.

I was testing with WebSocket.

I ran into it with REST.

Ok... so I moved the responsibility of the REST dispatching from the service bundle to StandardRequestTransformer.

In the transform method....


```java
if (metaData == null) {
            errorsList.add("Unable to find handler");
            return null;
        }
```

It says... hey.. I can't find nothing, but it does not then go into detail like we did before.

I agree that the detail was nice.

I will add logging to StandardRequestTransformer such that if info is true, then it will go through every method, and say.. here are the patch I know about. 

Not sure if this should be info or debug. :)

**Comment by revelfire** [comment]
Info if startup-based.  debug for runtime cases.  My .02.

On Mon, Jun 8, 2015 at 11:47 PM, Richard Hightower <notifications@github.com
> wrote:

> It is only for REST calls not WebSocket.
>
> I was testing with WebSocket.
>
> I ran into it with REST.
>
> Ok... so I moved the responsibility of the REST dispatching from the
> service bundle to StandardRequestTransformer.
>
> In the transform method....
>
> if (metaData == null) {
>             errorsList.add("Unable to find handler");
>             return null;
>         }
>
> It says... hey.. I can't find nothing, but it does not then go into detail
> like we did before.
>
> I agree that the detail was nice.
>
> I will add logging to StandardRequestTransformer such that if info is
> true, then it will go through every method, and say.. here are the patch I
> know about.
>
> Not sure if this should be info or debug. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/253#issuecomment-110224715>.
>



-- 
Thanks,
Chris

**Comment by RichardHightower** [comment]
fair enough.

On Mon, Jun 8, 2015 at 10:03 PM, revelfire <notifications@github.com> wrote:

> Info if startup-based. debug for runtime cases. My .02.
>
> On Mon, Jun 8, 2015 at 11:47 PM, Richard Hightower <
> notifications@github.com
> > wrote:
>
> > It is only for REST calls not WebSocket.
> >
> > I was testing with WebSocket.
> >
> > I ran into it with REST.
> >
> > Ok... so I moved the responsibility of the REST dispatching from the
> > service bundle to StandardRequestTransformer.
> >
> > In the transform method....
> >
> > if (metaData == null) {
> > errorsList.add("Unable to find handler");
> > return null;
> > }
> >
> > It says... hey.. I can't find nothing, but it does not then go into
> detail
> > like we did before.
> >
> > I agree that the detail was nice.
> >
> > I will add logging to StandardRequestTransformer such that if info is
> > true, then it will go through every method, and say.. here are the patch
> I
> > know about.
> >
> > Not sure if this should be info or debug. :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/advantageous/qbit/issues/253#issuecomment-110224715
> >.
> >
>
>
>
> --
> Thanks,
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/253#issuecomment-110226775>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
ok.. just added. let's see how it turns out.
