### ISSUE TITLE
How to get List<POJO> from service

### ISSUE THREAD

**Issue by ArcosBinary** [advantageous/qbit#262]
Hi, 
I'm using qbit-vertx version 0.7.2 as like as in your examples.
I have a service which creates a List<POJO>. I'm able 2 get this List with my Firefox and I can print this List using a CallBack. But my problem is that I need 2 get this List via httpRequest. 
I tried 2 parse the List 2 JSON, get them with a httpRequest and parse them back 2 List<POJO>.
But it doesn't work correctly. If I do something like:
```java
createTaskFromPojo(fromPOJO( pojoItem, POJO.class) );
```
I get the error that it's not possible 2 convert from JSON to my POJO, even it's still converted from JSON back to my own Model(POJO). If I test this case with a single Application: 
create a List<POJO> -> convert2JSON -> convertFromJSON ->createTaskFromPOJO

So I tried 2 get the List via ServiceInterface, but It seems not possible 2 get something just send.
I need something like: 
```java
List<POJO> load();
```
instead of 
```java
void load(Callback<List<POJO>> handler);
```
I really want 2 use qbit but u need 2 keep updating the wiki and commenting (JavaDoc) your code.
So what is the correct way to get my List<POJO> from a service?

**Comment by RichardHightower** [comment]
Not sure if I understand your question per se.

But let me break it down.


Here is a service....

package io.advantageous.qbit.examples;


import io.advantageous.qbit.annotation.RequestMapping;
import io.advantageous.qbit.annotation.RequestMethod;

import java.util.ArrayList;
import java.util.List;

/**
 * created by rhightower on 1/19/15.
 */

@RequestMapping("/todo-service")
public class TodoService {

    List<TodoItem> items = new ArrayList<>();


    @RequestMapping("/todo/count")
    public int size() {

        return items.size();
    }


    @RequestMapping("/todo/")
    public List<TodoItem> list() {
        return items;
    }


    @RequestMapping(value = "/todo", method = RequestMethod.POST)
    public void add(TodoItem todoItem) {
        items.add(todoItem);
    }

}


You bind this service to a port as follows:

package io.advantageous.qbit.examples;

import io.advantageous.qbit.server.EndpointServerBuilder;
import io.advantageous.qbit.server.ServiceEndpointServer;

public class TodoMain {

    public static void main(String... args) {

        ServiceEndpointServer server =
EndpointServerBuilder.endpointServerBuilder().setHost("localhost")
                .setPort(8080).build();

        server.initServices(new TodoService()).startServer();
    }

}



Once it it bound, then you can call it via http using curl.

QBit also has an http lib as follows:

package io.advantageous.qbit.examples;

import io.advantageous.boon.json.JsonFactory;
import io.advantageous.qbit.http.client.HttpClient;
import io.advantageous.qbit.http.client.HttpClientBuilder;
import io.advantageous.qbit.http.request.HttpResponse;
import io.advantageous.qbit.http.request.HttpTextReceiver;

import java.util.Date;

import static io.advantageous.boon.core.IO.puts;

/**
 * Created by rhightower on 6/8/15.
 */
public class TodoClientTest {

    public static void main(String... args) {
        final HttpClient httpClient =
HttpClientBuilder.httpClientBuilder().setPort(8080).build();
        httpClient.startClient();

        final HttpResponse httpResponse =
httpClient.get("/services/todo-service/todo/count");
        puts("COUNT BEFORE", httpResponse.body());

        httpClient.postJson(
                "/services/todo-service/todo",
                JsonFactory.toJson(new TodoItem("description", "name", new
Date())));


        httpClient.postJson(
                "/services/todo-service/todo",
                JsonFactory.toJson(new TodoItem("description1", "name1",
new Date())));


        httpClient.postJson(
                "/services/todo-service/todo",
                JsonFactory.toJson(new TodoItem("description2", "name2",
new Date())));

        final HttpResponse after =
httpClient.get("/services/todo-service/todo/count");
        puts("COUNT After", after.body());

        final HttpResponse listFromJson =
httpClient.get("/services/todo-service/todo/");

        puts("LIST After", listFromJson.body());


        puts("LIST After", JsonFactory.fromJsonArray(listFromJson.body(),
TodoItem.class));

    }
}

If you want to call things via websocket then you use the proxy interface
which is well documented.

I hope this helps.



On Mon, Jun 8, 2015 at 3:30 AM, ArcosBinary <notifications@github.com>
wrote:

> Hi,
> I'm using qbit-vertx version 0.7.2 as like as in your examples.
> I have a service which creates a List. I'm able 2 get this List with my
> Firefox and I can print this List using a CallBack. But my problem is that
> I need 2 get this List via httpRequest.
> I tried 2 parse the List 2 JSON, get them with a httpRequest and parse
> them back 2 List.
> But it doesn't work correctly. If I do something like:
>
> createTaskFromPojo(fromPOJO( pojoItem, POJO.class) );
>
> I get the error that it's not possible 2 convert from JSON to my POJO,
> even it's still converted from JSON back to my own Model(POJO). If I test
> this case with a single Application:
> create a List -> convert2JSON -> convertFromJSON ->createTaskFromPOJO
>
> So I tried 2 get the List via ServiceInterface, but It seems not possible
> 2 get something just send.
> I need something like:
>
> List<POJO> load();
>
> instead of
>
> void load(Callback<List<POJO>> handler);
>
> I really want 2 use qbit but u need 2 keep updating the wiki and
> commenting (JavaDoc) your code.
> So what is the correct way to get my List from a service?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/262>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by ArcosBinary** [comment]
Thanks for the answer. :)
Yeah, this looks exactly like my first try 2 get a List<POJO>. I guess you're using version 0.8.7 for this example? I couldn't find the full example in the wiki so I took code snipets from the repo. These version is still 0.7.2.
Give me a second 2 reproduce my problem :)

**Comment by RichardHightower** [comment]
Could be that we fixed things. 0.7.2 was a while back now.
We have been doing a lot of cleanup, and we revamped the way we handle REST
(a complete rewrite to handle multiple verbs, etc.)

On Tue, Jun 9, 2015 at 4:22 AM, ArcosBinary <notifications@github.com>
wrote:

> Thanks for the answer. :)
> Yeah, this looks exactly like my first try 2 get a List. I guess you're
> using version 0.8.7 for this example? I couldn't find the full example in
> the wiki so I took code snipets from the repo. These version is still 0.7.2.
> Give me a second 2 reproduce my problem :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/262#issuecomment-110321819>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
You want to use 0.8.8

On Tue, Jun 9, 2015 at 4:22 AM, ArcosBinary <notifications@github.com>
wrote:

> Thanks for the answer. :)
> Yeah, this looks exactly like my first try 2 get a List. I guess you're
> using version 0.8.7 for this example? I couldn't find the full example in
> the wiki so I took code snipets from the repo. These version is still 0.7.2.
> Give me a second 2 reproduce my problem :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/262#issuecomment-110321819>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by ArcosBinary** [comment]
Thanks 4 the tip. 
My DatabaseService works very well :)
