### ISSUE TITLE
PathVariable affected by @Service annotation, @Service annotation source package not regarded

### ISSUE THREAD

**Issue by revelfire** [advantageous/qbit#263]
Couple of interesting things here.  

1. When I include an @Service annotation the PathVariable suddenly has to be numeric (so a {0} that maps to 'String' gets broken).

2. It doesn't MATTER if my @Service annotation is from import io.advantageous.qbit.annotation.Service; or import org.springframework.stereotype.Service; - they both break this in the same way.

https://gist.github.com/revelfire/16d3ff737b5b40ede583

**Comment by RichardHightower** [comment]
weird

**Comment by RichardHightower** [comment]
I am betting that this is fixed now. 
But if not I am going to fix this today.

**Comment by RichardHightower** [comment]
This fix is in this pull request:

https://github.com/advantageous/qbit/pull/566
