### ISSUE TITLE
Wrong vertx status reason ?

### ISSUE THREAD

**Issue by ksubox** [advantageous/qbit#281]
Try to respond with 404 code instead 200 in EchoHttp.java example, but client receive "404 OK".
```
httpRequest.getReceiver().response(404, "application/json", toJson(results));
```
I guess wrong part is in DefaultHttpServerResponse.java (vertx ?):
```
  @Override
  public HttpServerResponse setStatusCode(int statusCode) {
    this.response.setStatus(new HttpResponseStatus(statusCode, response.getStatus().reasonPhrase()));
    return this;
  }
```
It takes old reason which is "OK".

**Comment by RichardHightower** [comment]
ok.. fixed.

**Comment by RichardHightower** [comment]
Please review change. 
https://github.com/advantageous/qbit/commit/77eefc57b30b797d62d9d158a0c2dbfc799e37c8
