### ISSUE TITLE
Any idea for Queue implementation compared with jctools ?

### ISSUE THREAD

**Issue by bwzhang2011** [advantageous/qbit#285]
From wiki of qbit, we've got to know that qbit made deep use of queue. just take famous nio framework netty for example, it did wrap the MPSC or else queue implementation originated from jctools(https://github.com/JCTools/JCTools/tree/master/jctools-core/src/main/java/org/jctools/queues) to improvement performance. so how about any idea for such between own and jctools. what's more, please take a look at such  https://github.com/bennidi/eventbus-performance/issues/1  while testing those queue performance.

**Comment by RichardHightower** [comment]
IDK QBit has been clocked at 200M messages per second with many writers. It seems to have some speed behind it. Nothing stops us in the future to use jctools. Right now, I think we are more focused on clean up and releasing something solid.

**Comment by bwzhang2011** [comment]
@RichardHightower, I think you're serious about such issue. for another side, you could split he queue implementation of qbit for individual component to share between us while you're full satisfied with its performance.

**Comment by RichardHightower** [comment]
I don't understand your comment. Explain it to me. Go slow. Who is "us"? What am I not serious about? Are you part of the jctools group? Also.. I accept pull requests.

**Comment by bwzhang2011** [comment]
@RichardHightower, sorry for my words for you to puzzle about. us means those who take interest in qbit as the one of the best implementation towards micro service.  by the way I'm not the group member of jctools just the api user to some extent. what's more, I've got to hear that discussion or suggestion is appreciated of so it is with such came up. just for myself it's amazing that qbit queue reach so high performance compared with jctools queue.

**Comment by RichardHightower** [comment]
That is the idea behind it. In theory, it would be easy to plugin different queue implementations.
In reality, I am caught up in the thick of thin things. :) Sorry if I came off rude. Comments are not always the best form of communication.

**Comment by RichardHightower** [comment]
btw.. we have a mailing and a chat. https://gitter.im/advantageous/qbit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Come join us. :) right now.. it is mostly just me in the chat saying random things to myself. :)

**Comment by bwzhang2011** [comment]
@RichardHightower, it doesn't really matter about this.  as I'm one of the programmers from china so it is with poor English with appropriate words sometimes.

**Comment by RichardHightower** [comment]
I am a programmer from America with poor English. Together we can rule the world!

**Comment by bwzhang2011** [comment]
@RichardHightower, yeah.  I just mean that in my environment without more English communication, so we chat and discuss pure out of our mother language Chinese. so if words with more points in english, it will be experienced under the translation way not out of the natural way.  I'm new comer towards micro service and it's introduced  from a famous website which introduced some new framework or idea around java world. here comes its introduction for qbit: http://www.jdon.com/47151 with such I've got to know that qbit is very fast and I just want to know how and how it could be integrated in our projects.

**Comment by bwzhang2011** [comment]
the only pity that qbit is limited in jdk8 and if qbit could take compatibility side at least jdk7, it would be widely used for there're a lot projects based jdk7 that want to build micro service for SOA way.
