### ISSUE TITLE
Any idea with qbit branch with support for JDK7

### ISSUE THREAD

**Issue by bwzhang2011** [advantageous/qbit#286]
QBit is excellent but one shortcoming that it designed for JDK8. but as you know there're many old projects with lower JDK like JDK7 at least. if those projects want to adopt the microservice like qbit as the provider, it will be a pity that those projects are hard to make use of qbit.

**Comment by RichardHightower** [comment]
QBit was first done on JDK 7. We decided to switch it to JDK 8. 
I think it is the right decision. 
This style of programming is much more fluent with JDK 8 lambda.
