### ISSUE TITLE
Removing /services/ from the URL prefix.

### ISSUE THREAD

**Issue by gencube** [advantageous/qbit#299]
Hi,

// From client side, this is the URL
http://localhost:8080/services/mrs/api/persons 

How to  change @RequestMapping(...) into JUST:
http://localhost:8080/mrs/api/persons 

Our existing client javascript rest services are mostly mapped to that URL.

**Comment by RichardHightower** [comment]
The ServiceServer has a URI.

The EndpointServerBuilder has a method called setURI.

services is the default URI.

just call setURI("mrs")


On Tue, Jul 7, 2015 at 11:35 PM, Matthew Ong <notifications@github.com>
wrote:

> Hi,
>
> // From client side, this is the URL
> http://localhost:8080/services/mrs/api/persons
>
> How to change @RequestMapping(...) into JUST:
> http://localhost:8080/mrs/api/persons
>
> Our existing client javascript rest services are mostly mapped to that URL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/299>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
I got the case wrong.

public EndpointServerBuilder setUri(String uri) { this.uri = uri; return
this; }

On Wed, Jul 8, 2015 at 10:52 AM, Rick Hightower <richardhightower@gmail.com>
wrote:

> The ServiceServer has a URI.
>
> The EndpointServerBuilder has a method called setURI.
>
> services is the default URI.
>
> just call setURI("mrs")
>
>
> On Tue, Jul 7, 2015 at 11:35 PM, Matthew Ong <notifications@github.com>
> wrote:
>
>> Hi,
>>
>> // From client side, this is the URL
>> http://localhost:8080/services/mrs/api/persons
>>
>> How to change @RequestMapping(...) into JUST:
>> http://localhost:8080/mrs/api/persons
>>
>> Our existing client javascript rest services are mostly mapped to that
>> URL.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/advantageous/qbit/issues/299>.
>>
>
>
>
> --
> *Rick Hightower*
> (415) 968-9037
> Profile <http://www.google.com/profiles/RichardHightower>
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
https://gist.github.com/RichardHightower/4bb3921edec2e663b955

Here is an example of how to change the root address from /services to
something else. And this is also an example of working with the Docker,
Mesos, Heroku friendly version of QBit.

package qbit.todo;
import io.advantageous.qbit.admin.ManagedServiceBuilder;
import io.advantageous.qbit.server.ServiceEndpointServer;

public class TodoRestServer {



    public static void main(String... args) {


        final ManagedServiceBuilder managedServiceBuilder =
ManagedServiceBuilder.managedServiceBuilder();

        final ServiceEndpointServer serviceServer =
managedServiceBuilder.getEndpointServerBuilder().setUri("/mrs")
                .build()
                .initServices(new TodoService()).startServer();

        /* Wait for the service to shutdown. */
        managedServiceBuilder.getSystemManager().waitForShutdown();

    }




}...package qbit.todo;
import io.advantageous.qbit.annotation.*;

/** * Created by rhightower on 2/10/15. */
@RequestMapping("/todoservice")public class TodoService {


    @RequestMapping("/todoo")
    public Todo list() {
        return new Todo("Hello");
    }

}...package qbit.todo;
public class Todo {
    private final String todo;
    private final long time = System.currentTimeMillis();

   public Todo(String todo) {
       this.todo = todo;
   }
}


You can run this curl command.

$  curl http://localhost:9090/mrs/todoservice/todoo
{"todo":"Hello","time":1436378304880}

With the ManagedServiceBuilder you can also get health and stats.

curl  http://localhost:9090/__stats/
{
    "MetricsKV": {},
    "MetricsMS": {},
    "MetricsC": {
        "TodoService": 1,
        "TodoService.startBatchCount": 2,
        "TodoService.receiveCount": 2
    },
    "version": 1
}

$ curl  http://localhost:9090/__health"ok"

There are flags to turn that off. And you also get a CTRL-C to nicely
shutdown all of the services. :)

It also reads $WEB_PORT and then $PORT from the enviroment variables. This
way is plays nice in Heroku or Docker or Mesos.

On Wed, Jul 8, 2015 at 10:53 AM, Rick Hightower <richardhightower@gmail.com>
wrote:

> I got the case wrong.
>
> public EndpointServerBuilder setUri(String uri) { this.uri = uri; return
> this; }
>
> On Wed, Jul 8, 2015 at 10:52 AM, Rick Hightower <
> richardhightower@gmail.com> wrote:
>
>> The ServiceServer has a URI.
>>
>> The EndpointServerBuilder has a method called setURI.
>>
>> services is the default URI.
>>
>> just call setURI("mrs")
>>
>>
>> On Tue, Jul 7, 2015 at 11:35 PM, Matthew Ong <notifications@github.com>
>> wrote:
>>
>>> Hi,
>>>
>>> // From client side, this is the URL
>>> http://localhost:8080/services/mrs/api/persons
>>>
>>> How to change @RequestMapping(...) into JUST:
>>> http://localhost:8080/mrs/api/persons
>>>
>>> Our existing client javascript rest services are mostly mapped to that
>>> URL.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/advantageous/qbit/issues/299>.
>>>
>>
>>
>>
>> --
>> *Rick Hightower*
>> (415) 968-9037
>> Profile <http://www.google.com/profiles/RichardHightower>
>>
>
>
>
> --
> *Rick Hightower*
> (415) 968-9037
> Profile <http://www.google.com/profiles/RichardHightower>
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
https://gist.github.com/RichardHightower/4bb3921edec2e663b955
