### ISSUE TITLE
HTTP Server register with consul

### ISSUE THREAD

**Issue by sailorgeoffrey** [advantageous/qbit#308]
Http server, as well as all service endpoint servers should register with consul because they listen on a port and should be discoverable.

**Comment by RichardHightower** [comment]
Should be easy to add. I will take a look.

On Mon, Jul 13, 2015 at 8:37 PM, Geoffrey Chandler <notifications@github.com
> wrote:

> Http server, as well as all service endpoint servers should register with
> consul because they listen on a port and should be discoverable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/308>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
