### ISSUE TITLE
Queue Depth Stats For All Services

### ISSUE THREAD

**Issue by sailorgeoffrey** [advantageous/qbit#309]
now that we have nice stats, we should include queue depths for all service queues.  This way when something starts filling a queue, we can see a graph growing before it finally stops working.

**Comment by RichardHightower** [comment]
Should be easy to add. I will take a look.

On Mon, Jul 13, 2015 at 8:38 PM, Geoffrey Chandler <notifications@github.com
> wrote:

> now that we have nice stats, we should include queue depths for all
> service queues. This way when something starts filling a queue, we can see
> a graph growing before it finally stops working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/309>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
I added this a while back.
