### ISSUE TITLE
Add ability to allow http server to set CORS headers

### ISSUE THREAD

**Issue by revelfire** [advantageous/qbit#353]
No way to set CORS headers that I can find.  Adding configurability on an "all responses" basis.

**Comment by RichardHightower** [comment]
ok so we need to add this 

This says allow web pages from http://mozilla.com to access our service or does it say allow this browser page to access our service. 

So we can add addCorsOrigin to ManagedServiceBuilder....

```
Access-Control-Allow-Origin: http://mozilla.com
```

I guess I am confused a bit.

You want a QBit service to be useable from JSON script running in a browser from another origina/website.

I guess these too

```
Access-Control-Allow-Methods
Access-Control-Allow-Headers
```

**Comment by RichardHightower** [comment]
started https://github.com/advantageous/qbit/pull/366

**Comment by RichardHightower** [comment]
related but opposite end...

https://github.com/advantageous/qbit/issues/355

**Comment by RichardHightower** [comment]
@revelfire back to you buddy.. the response decrator stuff is in the branch / pull request.

**Comment by RichardHightower** [comment]
I added the filter stuff. Did you try it out yet? Do you need docs for it?
You can see the code change and examples in the unit tests for the pull request.

**Comment by RichardHightower** [comment]
https://github.com/advantageous/qbit/pull/366
