### ISSUE TITLE
allow passing HttpRequest, MulitMap params, MultiMap headers, etc. from REST call

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#371]
allow passing HttpRequest, MulitMap params, MultiMap headers, etc. from REST call

**Comment by alexey-kanashevich** [comment]
+1 for this feature

**Comment by RichardHightower** [comment]
I accept pull requests. :)

**Comment by RichardHightower** [comment]
This is done. 
You turn on ManagedServiceBuilder.enableLoggingMappedDiagnosticContext or ManagedServiceBuilder.enableRequestChain.

Or you enable the AOP interceptors direct see

https://github.com/advantageous/qbit/wiki/%5BDocument%5D-MDC---Logging-Mapped-Diagnostic-Context,-RequestContext-and-HttpContext

Then you use RequestContext.getRequest()
