### ISSUE TITLE
when using consul service ServiceDiscovery. consul is not shutting down when we get a CTRL-C from spring app.

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#392]
when using consul service ServiceDiscovery. consul is not shutting down when we get a CTRL-C from spring app.

**Comment by RichardHightower** [comment]
We might have to register something to shut it down.

**Comment by sailorgeoffrey** [comment]
text here is a bit misleading... we aren't trying shutdown consul itself or its agent... just the service discovery that talks to it
