### ISSUE TITLE
Vertx 3.x support

### ISSUE THREAD

**Issue by mozinrat** [advantageous/qbit#418]
Hi Team, do we have vertex 3.0. Is there any dev build available with latest 3.x vertx apis embedded

**Comment by RichardHightower** [comment]
soon

**Comment by RichardHightower** [comment]
it is in master now

**Comment by mozinrat** [comment]
@RichardHightower its really wonderful, did u publish some beta builds on maven/jcenter. I would love to try and can help you in testing/feedbacks. Using the build 'io.advantageous.qbit:qbit-vertx:0.9.0.RELEASE' it reflects vertex 2.1.1.

**Comment by RichardHightower** [comment]
By COB today.

On Mon, Sep 28, 2015 at 11:58 AM, Rohit Verma <notifications@github.com>
wrote:

> @RichardHightower <https://github.com/RichardHightower> its really
> wonderful, did u publish some beta builds on maven/jcenter. I would love to
> try and can help you in testing/feedbacks. Using the build
> 'io.advantageous.qbit:qbit-vertx:0.9.0.RELEASE' it reflects vertex 2.1.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/418#issuecomment-143844099>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by mozinrat** [comment]
Oh thanks, really appreciate this and your dedication. Hats off sir:)

**Comment by mozinrat** [comment]
Is the RC1 released? Are you planing to release it to mavenCentral or any personal repository?

**Comment by RichardHightower** [comment]
http://search.maven.org/#artifactdetails%7Ccom.github.advantageous%7Cqbit-vertx%7C0.9.1-RC2%7Cjar

compile 'com.github.advantageous:qbit-vertx:0.9.1-RC2'

On Tue, Sep 29, 2015 at 8:57 AM, Rohit Verma <notifications@github.com>
wrote:

> Is the RC1 released? Are you planing to release it to mavenCentral or any
> personal repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/418#issuecomment-144102455>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by mozinrat** [comment]
I tried this with wrk as "wrk -d 5s -t 2 -c 1000 http://localhost:8081/root/hello/hello" and it gave me 
Sep 29, 2015 2:08:32 PM io.vertx.core.net.impl.ConnectionBase
SEVERE: java.io.IOException: Connection reset by peer

Is this the expected behaviour? Am I doing something wrong?

**Comment by RichardHightower** [comment]
https://github.com/advantageous/qbit/issues/421

Do you have a code listing?
