### ISSUE TITLE
Get rid of warpper exception and send root was system.out barf when handling errors in callbacks

### ISSUE THREAD

**Issue by sailorgeoffrey** [advantageous/qbit#443]
Say you have an exception in your service:
if (String.valueOf(result).contains("7")) throw new RuntimeException("Oh no!  Not a seven!");

Then you add an error handler to your callback:
.withErrorHandler(e -> logger.error("blew up: " + e.getMessage()))

it should say:
blew up:  Oh no!  Not a seven!

instead it says
blew up: unable to invoke method public int com.sailorgeoffrey.pinger.RandomNumberExample$$Lambda$9/1399701152.getRandom(int,int)  on object  com.sailorgeoffrey.pinger.RandomNumberExample$$Lambda$9/1399701152@28bb00e3 with arguments [0, 100] 
parameter types [int, int] 
argument types are [0, 100]

 CAUSE java.lang.RuntimeException :: Oh no!  Not a seven!

**Comment by RichardHightower** [comment]
It is not System.out

The issues is that it should send the nested exception but it sounds the outer exception instead.

This is a workaround.

```java
        for (int a = 0; a < 100; a++) {

            final AsyncFutureCallback<Integer> callback = CallbackBuilder.newCallbackBuilder()
                    .withCallback(l -> System.out.println("" + l))
                    .withErrorHandler(e -> System.out.println("blew up" +  e.getCause()))
                    .<Integer>build();
            randomNumberServiceAsync.getRandom(callback, 100, a);
        }

```

Noitce `e -> System.out.println("blew up" +  e.getCause())`

**Comment by RichardHightower** [comment]
I fixed this and improved exception handling for REST.
