### ISSUE TITLE
request body support in GET method

### ISSUE THREAD

**Issue by metanil** [advantageous/qbit#449]
This will violate HTTP/1.1 spec.

But may be useful if used properly.

ElasticSearch does this as well, since the query can be too big.

**Comment by RichardHightower** [comment]
Problem is most HTTP libs don't allow it.
I don't think there is anything in QBit that would prevent this.
But QBit http just delegates to Vertx Http support which uses Netty.
I think one of those two underlying libs are not supporting GET having a body.
