### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by FbN** [advantageous/qbit#483]
Hi. I have build a small websocket server following the README example. The service works but I have notice that the running server constantly consume CPU even when there is not any web call. How I can tune the qbit server to use less possible CPU on iddle? Thank you

**Comment by RichardHightower** [comment]
I will check it out.

On Thursday, October 22, 2015, Fabiano Taioli <notifications@github.com>
wrote:

> Hi. I have build a small websocket server following the README example.
> The service works but I have notice that the running server constantly
> consume CPU even when there is not any web call. How I can tune the qbit
> server to use less possible CPU on iddle? Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/483>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by ftaiolivista** [comment]
Thank you Richard, 

I have to run the server on Raspberry so every little CPU usage is important.

I have done a test running an empty server

httpServerBuilder().setPort(8080).build().start()

Even in this case che APP constantly use beetwen 2.9%-10% CPU usage (Raspberry P1)

![See HTOP screen](http://i.imgur.com/99G51MY.png)

Thank you
Fabiano

**Comment by RichardHightower** [comment]
I am able to reproduce this issue. 
I think I have a fix too.

I just refactored some of the low level queuing.

**Comment by RichardHightower** [comment]
You are the second person to report this.

**Comment by RichardHightower** [comment]
FIXED!

**Comment by RichardHightower** [comment]
Please check it for me.

**Comment by ftaiolivista** [comment]
Thank you for your ultra quick reply. I done some test but I don't see improvements.
I have uploaded a test app (an empty server https://github.com/ftaiolivista/qbit-cpu-test ). On the raspberry CPU usage is around 13% at zero call load. But I'm not sure if si a bad or good value.

![htop](http://i.imgur.com/8VCwlC3.png)

**Comment by RichardHightower** [comment]
The queues do wake up and check for repeating jobs, etc. You might want to set a much longer pollWait time. I assume you are building a snapshot?

**Comment by ftaiolivista** [comment]
Yes I'm building a snapshot. How I can customize poll/wait time? Is there other CPU consuming thinks I can disable (heal system, log system... ecc.)? Thank you.

**Comment by RichardHightower** [comment]
There is a builder called QueueBuilder is a property of several other builders.

**Comment by RichardHightower** [comment]
QueueBuilder has a setPollTime.. Try setting that.
