### ISSUE TITLE
@RequestParam, @PathVariable, @HeaderParam does not give null value for optional request param.

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#539]
For example if we have endpoint with Long, String as optional request param. If endpoint is  called without these params, then, Long comes in Long.MIN_VALUE and String comes with empty string (“”).

**Comment by RichardHightower** [comment]
The code in question is likely the 


```java


public class StandardRequestTransformer implements RequestTransformer {
...


    @Override
    public MethodCall<Object> transform(final HttpRequest request,
                                        final List<String> errorsList) {
        ...
        loop:
        for (ParameterMeta parameterMeta : parameters) {

            ParamType paramType = parameterMeta.getParam().getParamType();

            paramType = paramType == null ? ParamType.BODY : paramType;

            Object value;
            NamedParam namedParam;

            if (parameterMeta.getClassType() == Callback.class) {
                continue;
            }

            switch (paramType) {
                case REQUEST:
                    namedParam = ((NamedParam) parameterMeta.getParam());
                    value = request.params().get(namedParam.getName());

                    if (namedParam.isRequired() &&  Str.isEmpty(value)) {
                        errorsList.add(sputs("Unable to find required request param", namedParam.getName()));
                        break loop;

                    }
                    if (Str.isEmpty(value)) {
                        value = namedParam.getDefaultValue();
                    }
                    
                    value = value !=null ? decodeURLEncoding(value.toString()) : value;

                    break;

**Comment by RichardHightower** [comment]
One issue I have is that 

```java

@Retention(RetentionPolicy.RUNTIME)
@Target(value = {ElementType.PARAMETER})
public @interface RequestParam {

    String value() default "";

    boolean required() default false;

    String defaultValue() default "";

    /**
     * Used to document endpoint
     * @return description
     */
    String description() default "no description";


}
```

The default value is an empty String. 
It would be weird to make a string param take a null when the default value is "".

This is illegal in Java. 

```java

@Retention(RetentionPolicy.RUNTIME)
@Target(value = {ElementType.PARAMETER})
public @interface RequestParam {

    String value() default "";

    boolean required() default false;

    String defaultValue() default null; //ILLEGAL

    /**
     * Used to document endpoint
     * @return description
     */
    String description() default "no description";


}
```

For the case of number, I can specify that if primitive than 0.
If boolean, default is false if defaultValue is "".
If wrapper or object, default value is null if defaultValue is "".
What I have a problem with is making the default value a null if defaultValue is "".

**Comment by SagarN** [comment]
interesting language limitation :)

**Comment by RichardHightower** [comment]
WORKAROUND: Currently, If you set, defaultValue="0.0" then it would NOT get set to MIN_VALUE, it will become 0.0D or 0.0F or 0L or 0. Pretty sure about this.

But there is no current way to force a string to a null. And I am not sure how to do this. I think I am not.

I think.. 
I am going to do this:

For the case of number, I can specify that if primitive (int, short, long, etc.) than 0.
If boolean, default is false if defaultValue is "".
If wrapper or object, default value is null if defaultValue is "".
If string default value is "" if defaultValue is "".

Not sure how else to handle it. More worried about unexpected NPE than defaultValue being "" for string. 

The defaultValue will be a string that gets parsed to the primitive type (or enum or basic type).

**Comment by RichardHightower** [comment]
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestParam.html

**Comment by RichardHightower** [comment]
It looks like spring sets the defaultValue to this "\n\t\t\n\t\t\n\ue000\ue001\ue002\n\t\t\t\t\n" and not "". So then they just check to see if it was set by looking at the default values is equals that that long unique string. I can do that too. So I can support null for String and still have a decent defaultValue.
