### ISSUE TITLE
Unable to open WebSocket connection

### ISSUE THREAD

**Issue by janithb** [advantageous/qbit#559]
I got below error message when running WebSocket example with below dependencies.

qbit-vertx - 0.8.18
qbit-boon - 0.8.18

>host localhost 
>port 8080

>2015-11-25 18:00:47 DEBUG ScheduledThreadContext:72 - Started:null
>2015-11-25 18:00:47 DEBUG WebSocketClientHandshaker13:81 - WebSocket version 13 client handshake key: fZaybUIDYeLBaRih6NxGyg==, expected response: 1WSWX5lFYS0Iir9N0QgVaOfa9UU=
>2015-11-25 18:00:47 DEBUG JavassistTypeParameterMatcherGenerator:76 - Generated: io.netty.util.internal.__matchers__.io.netty.handler.codec.http.websocketx.WebSocketFrameMatcher
Exception in thread "main" java.lang.IllegalStateException: Unable to open WebSocket connection
	at io.advantageous.qbit.network.impl.NetSocketBase.openAndWait(NetSocketBase.java:190)
	at org.audit4j.microservice.transport.Sample.main(Sample.java:37)
>2015-11-25 18:00:47 DEBUG WebSocketServerHandshaker:81 - [id: 0x29f93c94, /127.0.0.1:54688 => /127.0.0.1:8080] WebSocket version V13 server handshake
>2015-11-25 18:00:47 DEBUG WebSocketServerHandshaker:81 - WebSocket version 13 server handshake key: fZaybUIDYeLBaRih6NxGyg==, response: 1WSWX5lFYS0Iir9N0QgVaOfa9UU=
>2015-11-25 18:00:56 INFO  HttpServerVertx:146 - Exception Count 0 Close Count 0

**Comment by janithb** [comment]
Issue is resolved after upgrading the dependencies to below versions

qbit-core - 0.9.1.RELEASE
qbit-boon - 0.9.0.RELEASE
qbit-vertx - 0.9.1.RELEASE

**Comment by RichardHightower** [comment]
Ok. In general, it is better to use the latest release. I am not sure why it did not work with 0.8.x. It should have but if upgrading it made it work, then I am just going to close this. Thanks.

**Comment by RichardHightower** [comment]
This should be fixed
