### ISSUE TITLE
# of NoCache Header entry increments in every request if @NoCacheHeader is uses.

### ISSUE THREAD

**Issue by metanil** [advantageous/qbit#575]
To handle headers, Vertx uses 
```io.netty.handler.codec.http.DefaultHttpHeaders#set(java.lang.CharSequence, java.lang.Iterable<?>)``` which is called by ```io.advantageous.qbit.vertx.http.server.VertxHttpResponseReceiver#response(int, java.lang.String, java.lang.Object, io.advantageous.qbit.util.MultiMap<java.lang.String,java.lang.String>)```
and set all the value in that Iterable to CharSequence header key.

(From PR Add header controls to REST support and NoCache header controls
https://github.com/advantageous/qbit/pull/541/files)

In Qbit, ServiceMetaBuilder and ContextMetaBuilders, ```private MultiMap<String, String> getResponseHeaders(final Annotated annotated)``` need to make sure that it won't add multiple values for the same key.

Since it uses MultiMap, there could potentially multiple entry of value (for that key), as internally it stores as List (not as Set).

**Comment by RichardHightower** [comment]
Ok. Looking into this now. 

From your description, I should be able to enable NoCache header control, send a curl command and see it continue to increase every time I send a curl command. I will run curl -v.

**Comment by RichardHightower** [comment]
First no cache...


```java
package io.advantageous.qbit.example.nocache;


import static io.advantageous.qbit.admin.ManagedServiceBuilder.managedServiceBuilder;
import io.advantageous.qbit.annotation.RequestMapping;

@RequestMapping("/")
public class NoCacheService {

    @RequestMapping
    public String hello() {
        return "hello";
    }

    public static void main(final String... args) {
        managedServiceBuilder().setRootURI("/").addEndpointService(new NoCacheService()).startApplication();
    }
}

```

```sh
$ curl http://localhost:8080/hello -v
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"hello"
```

**Comment by RichardHightower** [comment]
Now with cache control...

```java
package io.advantageous.qbit.example.nocache;


import static io.advantageous.qbit.admin.ManagedServiceBuilder.managedServiceBuilder;
import io.advantageous.qbit.annotation.RequestMapping;
import io.advantageous.qbit.annotation.http.NoCacheHeaders;

@RequestMapping("/") @NoCacheHeaders
public class NoCacheService {

    @RequestMapping
    public String hello() {
        return "hello";
    }

    public static void main(final String... args) {
        managedServiceBuilder().setRootURI("/").addEndpointService(new NoCacheService()).startApplication();
    }
}

```

```sh
$ curl http://localhost:8080/hello -v
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"hello"Richards-MacBook-Pro-3:qbit-project rick$ curl http://localhost:8080/hello -v
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=0
< Cache-Control: no-cache, no-store
< Content-Type: application/json
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"hello"Richards-MacBook-Pro-3:qbit-project rick$ curl http://localhost:8080/hello -v
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=0
< Cache-Control: no-cache, no-store
< Content-Type: application/json
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"hello"Richards-MacBook-Pro-3:qbit-project rick$ curl http://localhost:8080/hello -v
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=0
< Cache-Control: no-cache, no-store
< Content-Type: application/json
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"hello"Richards-MacBook-Pro-3:qbit-project rick$ 

```

I do not see it increasing.

**Comment by RichardHightower** [comment]
HTTP RFC2616 available here says:

Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded
So, multiple headers with the same name is ok (www-authenticate is such a case) if the entire field-value is defined as a comma-separated list of values.

Cache-control is documented here: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9 like this:

Cache-Control   = "Cache-Control" ":" 1#cache-directive
The #1cache-directive syntax defines a list of at least one cache-directive elements (see here for the formal definition of #values: Notational Conventions and Generic Grammar)

So, yes,

Cache-Control: no-cache, no-store
is equivalent to (order is important)

Cache-Control: no-cache
Cache-Control: no-store

http://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
