### ISSUE TITLE
qbit doesn't support service created by guice with method interceptor module.

### ISSUE THREAD

**Issue by maratfdrv** [advantageous/qbit#596]
I have warning in my log.

ServiceBuilder: QBit does not support method overloading methods in Service Queues problem name check is overloaded [CGLIB$findMethodProxy, longPollingBuilder,  CGLIB$check$5, react, handleRuntimeException, CGLIB$SET_THREAD_CALLBACKS, check, CGLIB$SET_STATIC_CALLBACKS] from class com.stedify.core.util.test.ThrowHandlerEndpoint$$EnhancerByGuice$$40f5be55

**Comment by RichardHightower** [comment]
should be fine. annoying warning but the generated guice methods should not hurt QBit.

**Comment by maratfdrv** [comment]
I investigated this problem.

I had error "Unable to find body" in  StandardRequestTransformer. Seems somewhere thinks that request should pass json or post param but I call http get method with request params.
  
@RequestMapping("/changeState")
    public void changeState(
            final Callback<Boolean> callback,
            @RequestParam("id") final String pubId,
            @RequestParam("state") final String state
    ) {
  

I found that MethodAccess class return same name for CGLIB$changeState$5 and changeState method and  in this code in ServiceMetaBuilder.

requestMetaBuilder.addParameters(rootPath, servicePath, path, methodAccess)

calculates request types  by CGLIB$changeState$5 but it doesn't have any  RequestParam annotations.

**Comment by RichardHightower** [comment]
hmm.. not sure how it does that. Can you add sample code somewhere in github so I can take a look? If I can reproduce it, I can likely fix it.

**Comment by maratfdrv** [comment]
I've created PR with broken test. If you delete `@Auth` annotation from `UserEndpoint` class then guice method interceptor module  will be  disable and `GuiceTest` passes.

**Comment by maratfdrv** [comment]
I've added brute fix for it.... Maybe you like it.

**Comment by RichardHightower** [comment]
you patch fixed this.. so can I close this now?
