### ISSUE TITLE
Ignored websocket calls to the rest API

### ISSUE THREAD

**Issue by cazacugmihai** [advantageous/qbit#610]
Hi,

I tried to make some calls to a rest API via websocket (using a proxy) and the calls are not triggered.
Here you can find the application (rest + websocket classes): [reproducer.zip](https://github.com/advantageous/qbit/files/90483/reproducer.zip).

Thanks,
Mihai

**Comment by RichardHightower** [comment]
Put your example in a gist or in github or inline.

**Comment by RichardHightower** [comment]
This is a common feature and it works. We want to put this in git or gist so we can help. Closing for now.

**Comment by RichardHightower** [comment]
I fixed this.
