### ISSUE TITLE
Cant start qbit websocket standalone example

### ISSUE THREAD

**Issue by masaykh** [advantageous/qbit#617]
Untouched download, last stable realese, eclipse, without gradle (i dont use gradle only maven).

i put breakpoint on 
  HttpServer httpServer = httpServerBuilder().setPort(8080).build();
in debugger last place before NullPointerExpection is
    public static HttpServerFactory getHttpServerFactory() {
        return httpServerFactoryRef.get();
    }
in FactoryPsi.java
debbuger show that httpServerFactoryRef == null
and breakpoint placed on setHttpServerFactory, dont showedup.

so maybe it is not so standalone? or there is someway to set it?

full stacktrace : 
Exception in thread "main" java.lang.NullPointerException
	at io.advantageous.qbit.Factory.createHttpServer(Factory.java:394)
	at io.advantageous.qbit.http.server.HttpServerBuilder.build(HttpServerBuilder.java:226)
	at websocket.EchoWebSocket.main(EchoWebSocket.java:39)

**Comment by RichardHightower** [comment]
QBit does not have an IO lib.
It uses Vertx as an IO lib. You will need to include the qbit-vertx jar.
