### ISSUE TITLE
Doesn't support hibernate annotation or others for service body parameter.

### ISSUE THREAD

**Issue by maratfdrv** [advantageous/qbit#618]
```
    @RequestMapping(value = "/register", method = RequestMethod.POST)
    public SessionModel register(
        @Valid RegisterModel registerModel
    ) {
        return new SessionModel(userService.register(registerModel));
    }
```
registerModel should be body parameter.

**Comment by RichardHightower** [comment]
if RegisterModel is just a pojo.. this should work flawlessly.. can you help me understand what is happening and provide some more background.

**Comment by maratfdrv** [comment]
This happens in RequestMetaBuild.addParams. if parameter has annotation qbit thinks  it should be one of requestParam, headerParam or pathParam.

**Comment by RichardHightower** [comment]
ic... Can you create a PR?
