### ISSUE TITLE
Local Proxy Gen to support returning Reakt invokeable promise

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#675]
Local Proxy Gen to support returning Reakt invokeable promise

```java

        employeeService.lookupEmployee("123")
               .then((employee)-> {...}).catchError(...).invoke();

```

It should support reactor too.

```java

        employeeService.lookupEmployee("123")
               .reactor(mgmt.reactor())
               .then((employee)-> {...}).catchError(...).invoke();

```

https://github.com/advantageous/reakt/issues/17

**Comment by revelfire** [comment]
Not enough info here to fully grasp the "local proxy gen" aspect of the title.

**Comment by RichardHightower** [comment]
Take a look at this: 
https://github.com/advantageous/reakt/wiki/Invokable-Promise

**Comment by RichardHightower** [comment]
Then look at the code changes done in this PR.

https://github.com/advantageous/qbit/pull/681

**Comment by RichardHightower** [comment]
Where you really want to focus to understand this is to look at this test... https://github.com/advantageous/qbit/blob/master/qbit/core/src/test/java/io/advantageous/qbit/reakt/ReaktTest.java

**Comment by RichardHightower** [comment]
and by that test.. I really meant this one...

Where you really want to focus to understand this is to look at this test... 

https://github.com/advantageous/qbit/blob/master/qbit/vertx/src/test/java/io/advantageous/qbit/vertx/ReaktInterfaceTest.java

**Comment by RichardHightower** [comment]
This test is simpler 
https://github.com/advantageous/qbit/blob/master/qbit/core/src/test/java/io/advantageous/qbit/reakt/ReaktInterfaceTest.java and shows exactly what issue I am talking about.
