### ISSUE TITLE
Things I don't like

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#68]
GET is the default for REST
I think it should be POST for methods that take arguments, and GET for methods that do not. 

objectName is getting set by all proxies. 
It seems like it should not.

**Comment by revelfire** [comment]
Concur. Would rather NOT see method args handled as get parms or things
wind up being some one way and some another plus it would make parms
exposed in logs and such.

Could be a tricky thing for a new consumer though so this default behavior
would need to be well documented.  "Why does it work sometimes and not
others!?  Arghghh!!?!?"  - best avoided.

On Mon, Jan 19, 2015 at 7:26 PM, Richard Hightower <notifications@github.com
> wrote:

> GET is the default for REST
> I think it should be POST for methods that take arguments, and GET for
> methods that do not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/68>.
>



-- 
Thanks,
Chris

**Comment by RichardHightower** [comment]
Qbit is different in that it does have default mappings so their is some
convention over config but not sure I did it right. You can always
configure to remove all doubt.

On Monday, January 19, 2015, revelfire <notifications@github.com> wrote:

> Concur. Would rather NOT see method args handled as get parms or things
> wind up being some one way and some another plus it would make parms
> exposed in logs and such.
>
> Could be a tricky thing for a new consumer though so this default behavior
> would need to be well documented. "Why does it work sometimes and not
> others!? Arghghh!!?!?" - best avoided.
>
> On Mon, Jan 19, 2015 at 7:26 PM, Richard Hightower <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > wrote:
>
> > GET is the default for REST
> > I think it should be POST for methods that take arguments, and GET for
> > methods that do not.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/advantageous/qbit/issues/68>.
> >
>
>
>
> --
> Thanks,
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/68#issuecomment-70598455>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
i think I will leave it as GET.
