### ISSUE TITLE
Client for WebSocket RPC does not work as expected with discovery service

### ISSUE THREAD

**Issue by id-regis** [advantageous/qbit#729]
Hi,

When creating a Client proxy with an associated service discovery, if the service  can't be loaded during the build (see: [here](https://github.com/advantageous/qbit/blob/f54ae4ef39e0fb942c8ddbb49cccb9ecd536aa26/qbit/core/src/main/java/io/advantageous/qbit/client/ClientBuilder.java#L288)) a default port (8080) and host (localhost) is used.

On the first attempt to send a websocket message the BoonClient try to open the socket [here](https://github.com/advantageous/qbit/blob/fce7f6faf30cdfb8f4762f4ee973556243f39278/qbit/core/src/main/java/io/advantageous/qbit/boon/client/BoonClient.java#L213-216). But fail to open websocket in [Http client](https://github.com/advantageous/qbit/blob/fce7f6faf30cdfb8f4762f4ee973556243f39278/qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/client/HttpVertxClient.java#L403) as the port and host are incorrect (so vertxWebSocket attribute remain at null which will cause NullPointerException later).

On a second attempt even if the service become available on the default port/host, message can't be send because sendText method is called [here](https://github.com/advantageous/qbit/blob/fce7f6faf30cdfb8f4762f4ee973556243f39278/qbit/core/src/main/java/io/advantageous/qbit/boon/client/BoonClient.java#L218) without retrying to open the websocket resulting in NullPointerException in [HttpVertxClient](https://github.com/advantageous/qbit/blob/fce7f6faf30cdfb8f4762f4ee973556243f39278/qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/client/HttpVertxClient.java#L394)

What I expect from the proxy client is :
- At start if the service is not available in service discovery catalog then mark Boon client as not connected, and set port/hostname to null in its Http server proxy client. (then do no accept to send message until service become available)
- When service become available, Boon client should receive a notify from service discovery
- In the notify callback port/hostname should be set
- In Boon Client send method should not call webSocket.sendText(message); if we are not connected, this [condition](https://github.com/advantageous/qbit/blob/fce7f6faf30cdfb8f4762f4ee973556243f39278/qbit/core/src/main/java/io/advantageous/qbit/boon/client/BoonClient.java#L212) should be changed to allow a retry before trying to send message.

Thanks

**Comment by RichardHightower** [comment]
Thanks for the detailed description. 
I will take a look.
Feel free to submit a patch.
