### ISSUE TITLE
How to send different HTTP status codes in the same method callback

### ISSUE THREAD

**Issue by brunoais** [advantageous/qbit#748]
Hi,  
I'm implementing a service that is planned to work such that the success of a request can either return either `201 Created` or `200 OK` depending if a resource was either created or replaced. The HTTP method will be the same: `PUT`.

I've been reading the documentation but I can't find any way of doing that. The method that responds would have to know what to return at compile time through the annotation. How do I set a status code individually for each request?

Additionally, I need the library that I use to work asynchronously. I already noticed this is async by default but I need any answer you give to be compatible with handling an HTTP request asynchronously.

Thanks in advance.

**Comment by brunoais** [comment]
Additionally, how do I do to send a `409 Conflict` or a `400 Bad Request` if the user sends bad information in the body?

**Comment by RichardHightower** [comment]
http://rick-hightower.blogspot.com/2015/10/we-have-been-busy-over-at-qbit-java.html

**Comment by brunoais** [comment]
Do you mean `HttpStatusCodeException.httpError()`?
That seems to be for errors only. It is quite flexible yes but it doesn't seem to be thought for making stuff that can either return a `200 OK` or a `201 Created` (do not forget that 201 requires a `Location:` header that has to be set)

**Comment by RichardHightower** [comment]
You could

```java
  @RequestMapping(value = "/helloj7", code = 221)
```

You can also do this:

```java
      @RequestMapping(method = RequestMethod.GET)
        public void ping2(Callback<HttpTextResponse> callback) {

            callback.returnThis(HttpResponseBuilder.httpResponseBuilder()
                    .setBody("hello mom").setContentType("mom")
                    .setCode(777)
                    .buildTextResponse());
        }
```

**Comment by RichardHightower** [comment]
`HttpResponseBuilder.httpResponseBuilder()` allows you to set a location header

**Comment by brunoais** [comment]
Ah! The `code` in `.setCode()` is the status code. OK, got it! Sounds good.
Thank you for your answers!

**Comment by RichardHightower** [comment]
You are welcome. Thanks for using QBit.
