### ISSUE TITLE
OutOfMemory Error in Reactor

### ISSUE THREAD

**Issue by tnegi7519** [advantageous/qbit#770]
We have observed OOM error while using the reactor.
On heap analysys we found the leakage is at 
BlockingQueue<CallbackCoordinator> removeCoordinatorQueue = new LinkedTransferQueue<>();

We are blocked because of this error.
![qbitoom](https://cloud.githubusercontent.com/assets/22950779/20628987/3367f07a-b34f-11e6-81ac-0142d00ef311.png)

**Comment by tnegi7519** [comment]
Please have a look at this issue

**Comment by RichardHightower** [comment]
Send a test case. 
This is most likely a programming mistake. 
We use qbit as a rate limiter in front of all of the services for a large media company.
