### ISSUE TITLE
gradle run issue 

### ISSUE THREAD

**Issue by fadihub** [advantageous/qbit#78]
when you run todo service it gets stock at buding 75%.
"13:44:36.140 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
13:44:36.140 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
13:44:36.140 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
13:44:36.140 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
13:44:36.141 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
13:44:36.141 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
13:44:36.249 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xf6f1f3b6f40abbf0
13:44:36.267 [main] DEBUG i.n.channel.ChannelOutboundBuffer - -Dio.netty.threadLocalDirectBufferSize: 65536
13:44:36.270 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
13:44:36.314 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
13:44:36.329 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
13:44:36.356 [main] INFO  i.a.qbit.vertx.http.HttpServerVertx - HTTP SERVER started on port 8080 host localhost
> Building 75% > :run

**Comment by RichardHightower** [comment]
ah
mine says 75% too
it just means it had to clean (25%), and build (25%), run tests (25%) and now it is jsut waiting for it to run (25%0

13:46:02.318 [main] INFO  i.a.qbit.vertx.http.HttpServerVertx - HTTP SERVER started on port 8080 host localhost
> Building 75% > :run
